name: Continuous Integration

on: [push]

jobs:
  build:
    name: Debbuging Project
    runs-on: ubuntu-latest
    environment: Compilação
    steps: 
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.302'
    - name: Build Project
      run: dotnet build Eschody.Application/Eschody.Application.csproj

  tests:
    name: Domain Tests
    runs-on: ubuntu-latest
    needs: build
    environment: Testes
    steps:
      - uses: actions/checkout@v1
      - name: Run Domain Tests
        run: dotnet test Eschody.Domain.Tests
      - uses: actions/checkout@v1
      - name: Run Services Tests
        run: dotnet test Eschody.Services.Tests