name: Continuous Integration

on: [pull_request]

jobs:
  build:
    name: Debbuging Project
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.302'
    - name: Build Project
      environment: Compilação
      run: dotnet build Eschody.Application.csproj

  tests:
    name: Domain Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v1
      - name: Run Domain Tests
        environment: Testes;
        run: dotnet test Eschody.Domain.Tests
      - name: Run Services Tests
        environment: Testes;
        run: dotnet test Eschody.Services.Tests